name: CI

on:
    push:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                  node-version: '18.17.x'
            - name: Install dependencies
              uses: borales/actions-yarn@v4
              with:
                  cmd: install --force
            - name: Build project
              uses: borales/actions-yarn@v4
              with:
                  cmd: build
            - name: Upload artifacts
              uses: actions/upload-artifact@v1
              with:
                  name: build
                  path: build
    deploy:
        needs: [build]
        runs-on: ubuntu-latest
        steps:
            - name: Download artifacts
              uses: actions/download-artifact@v1
              with:
                  name: build
            - name: Deploy files
              uses: appleboy/scp-action@v0.0.6
              with:
                  host: ${{ secrets.HOST }}
                  username: ${{ secrets.USERNAME }}
                  key: ${{ secrets.KEY }}
                  source: 'build/*'
                  target: 'sudoku'
                  overwrite: true
                  strip_components: 1
